services:
  postgres:
    image: postgres:16-alpine
    container_name: order-saga-postgres
    environment:
      POSTGRES_DB: order_saga
      POSTGRES_USER: order_saga
      POSTGRES_PASSWORD: order_saga
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: order-saga-redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    container_name: order-saga-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: order-saga-kafka-ui
    ports:
      - "8085:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-order-saga
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092